# @format

name: Update Documentation
on:
  pull_request:
    branches: [main]

jobs:
  run:
    name: Generate Documentation README
    runs-on: ubuntu-latest
    env:
      COMMIT_USER: GitHub Actions
      COMMIT_EMAIL: actions@github.com
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean install npm dependencies
        run: npm ci
      - name: Update documentation
        run: npm run docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ env.COMMIT_USER }}
          author_email: ${{ env.COMMIT_EMAIL }}
          message: '📝 Updating Docs [ci skip]'
          # Configure for custom directories if required
          # add: '.' # default '.'
